### ISSUE TITLE
V0.1.0 Minor bugs and issues

### ISSUE THREAD

**Issue by lisalin333** [ErnestLeung52/Onyx-InvoGen-Host#1]
1. Screenshot template not displaying fees, wherears invoice template does
2. Window closed period calculation is weird
3. Last four digit of CC is unrealistic
4. Setting buttons are covered by the profile component when profile list gets too long
5. Adding the same product twice will add separately to the cart

**Comment by ErnestLeung52** [comment]
Thank you for your feedback.
All bugs and issues from your comment have been addressed.
Please update the app version to V0.0.1.

Cheers 😀
Ernest

**Comment by ErnestLeung52** [comment]
> 1. Screenshot template not displaying fees, wherears invoice template does
> 2. Window closed period calculation is weird
> 3. Last four digit of CC is unrealistic
> 4. Setting buttons are covered by the profile component when profile list gets too long
> 5. Adding the same product twice will add separately to the cart

Thank you for your feedback!
All issues and bugs related to your comment have been addressed.
Please update your application to V0.0.1.

Cheers 😃
Ernest
